# -*- coding: utf-8 -*-
"""mini-chatgpt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wWTY5mShp-VnNrjtNwvNriM4mr3utM1

#Import Openai package
"""

!pip install openai

import openai

"""#Get 'apikey' from your openai account

you should buy an account :)
"""

apikey = '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'

openai.api_key = apikey

"""#Creat a robot and prompt a question"""

Question="Who is the most famous Iranian expert in the field of artificial intelligence?"

robot=openai.Completion.create(
    engine="text-davinci-003",
    prompt=Question,
    max_tokens=1024,
    n = 1,
    stop = None,
    temperature = 0.9
)

answer=robot.choices[0].text
print(answer)

"""Greats!
We did it!
"""